dist: trusty

language: python
python:
  - "2.7"

env:
  fast_finish: true

install:
  - pip install -e .
  - pip install pep8

script:
  - nosetests -v
  - pep8 --show-source .
  - python setup.py sdist

deploy:
  provider: pypi
  distributions: "sdist"
  user: pzhokhov
  password:
    secure: "FkfIvyF3PReaXOuCNSeqlg9SAiocc8WxCzlbqnfssG6JxsIBWNuoOPtgKtiYmMO+LBXnzpZ8CkTjoHT2oWWBD8r92QNmdIOze1MPs5xQmGxu12TEc5dEgMUnvenV3vkOZGC/hhwbio16Dqfd8PlHYBRkduvvqrvRD1xJPsggx9tgZwZ+Vvv0h51/BpOIMxm0xV3qu1U5A3BIvyzTUucvCAPbmHeZj+tWtiTq3OEwpc812PsCNkFNEOIBUkwafu1VE15tFcud/pZyFYwEK8/z35CJDGY4oVKWZyoC5/Gp9w658ps6MnjWP36Y1GNj4wpQPL2ftvGzRfXvfZ/FcSi4mreon24YPYFlY76ezLibWq8m2/ZBlQQwchFi48nGoalDJ7a92hyVkrRr1UP87+fbrZW8u4l/2HiKYKgotAixnoKKVOaWcmhraLve+kLE5F6e0lwmwCOHQwO9Cz4PECiZtxf8ePdDj+Dr9RLI3rKehRATpL+kXkR4WzKXPJAfDiPS6WiOz/melZJIttQcFZpOUVCs79yKWj8E95atbEy0jFaGn1PR+lFHqFYsg8TTe9Q9L/qMc+ECzBzQ4ryClCKDMYylCqbfDpOmCtHZw0a79IKmSyyvNbjnFMhAcn+GHFp+O46iF7Zxb1fAmp45AZ48bG/FCVqp66EXr590Fy1gjh0="
  on:
    # tags: true
    # branch: master
