database:
    type: http
    serverUrl: http://localhost:5000
    authentication:
        type: github

storage:
    type: gcloud
    bucket: studioml-sentient-artifacts



queue: local

saveMetricsFrequency: 1m
saveWorkspaceFrequency: 1m
verbose: error

cloud:
    gcloud:
        zone: us-central1-f

resources_needed:
    cpus: 2
    ram:  3g
    hdd:  10g
    gpus: 0

sleep_time: 1
worker_timeout: 30

optimizer:
    cmaes_config:
        popsize: 100
        sigma0: 0.25
        load_best_only: false
    load_checkpoint_file:
    visualization: true
    result_dir: "~/Desktop/"
    checkpoint_interval: 0
    termination_criterion:
        generation: 5
        fitness: 999
        skip_gen_thres: 1.0
        skip_gen_timeout: 30
